# Generated by Django 5.0 on 2025-01-14 10:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
