/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppointmentGetOut
 */
export interface AppointmentGetOut {
    /**
     * 
     * @type {Date}
     * @memberof AppointmentGetOut
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof AppointmentGetOut
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentGetOut
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentGetOut
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof AppointmentGetOut
     */
    id: string;
}

/**
 * Check if a given object implements the AppointmentGetOut interface.
 */
export function instanceOfAppointmentGetOut(value: object): value is AppointmentGetOut {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AppointmentGetOutFromJSON(json: any): AppointmentGetOut {
    return AppointmentGetOutFromJSONTyped(json, false);
}

export function AppointmentGetOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppointmentGetOut {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'email': json['email'],
        'description': json['description'],
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
    };
}

export function AppointmentGetOutToJSON(json: any): AppointmentGetOut {
    return AppointmentGetOutToJSONTyped(json, false);
}

export function AppointmentGetOutToJSONTyped(value?: AppointmentGetOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': ((value['date']).toISOString()),
        'email': value['email'],
        'description': value['description'],
        'created_at': ((value['createdAt']).toISOString()),
        'id': value['id'],
    };
}

